name: "Setup Environment"
description: "Setup Node.js, pnpm and install dependencies"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  pnpm-version:
    description: "pnpm version"
    required: false
    default: "9"
  cache-turbo:
    description: "Cache turbo build artifacts"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          node-modules-

    - name: Cache turbo build
      if: inputs.cache-turbo == 'true'
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          **/dist
        key: turbo-build-${{ github.sha }}
        restore-keys: |
          turbo-build-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
