name: Publish Packages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup-action
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build packages
        run: pnpm build-targets

      - name: Configure NPM
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm config set provenance true

      - name: Run Lerna publish (no push)
        run: pnpm lerna publish --yes --conventional-commits --no-push

      - name: Re-install to refresh lockfile
        run: pnpm install

      - name: Amend lockfile if changed
        run: |
          if ! git diff --quiet pnpm-lock.yaml; then
            git add pnpm-lock.yaml
            git commit --amend --no-edit
          fi

      - name: Push commit and tags
        run: |
          git push origin $GITHUB_REF_NAME --follow-tags
