name: Generate Release Notes

on:
  push:
    tags:
      - "v*"

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup-action
        with:
          cache-turbo: false

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            packages/*/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
